name: Build .btcpay plugin

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: [".github/workflows/build-plugin.yml"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish plugin
        run: dotnet publish BTCPayServer.Plugins.Trocador/BTCPayServer.Plugins.Trocador.csproj -c Release -o publish

      - name: Pack plugin
        run: dotnet run -c Release --project btcpayserver/BTCPayServer.PluginPacker -- "$GITHUB_WORKSPACE/publish" BTCPayServer.Plugins.Trocador "$GITHUB_WORKSPACE/packed"

      - name: List output
        run: find packed -type f -exec ls -l {} \;

      - uses: actions/upload-artifact@v4
        with:
          name: trocador-btcpay-plugin
          path: packed/**
